### PR TITLE
Issue 58 - Improve text_entry behavior 

### PR DESCRIPTION
**Pull request by B-Souty**
__What issue are you solving? (Give #issuenumber)__

* Issue #58.

__How do you solve it? (please write this so a human can understand it - bulletpoints are okay)__

* I am enabling 'focus_set' on text_entry to mak eit active when user reach the UsernameGUI screen
* I binded the 'Return' key to the already existing save_and_close method.

__If there is something specific in your solution, that you would like the reviewer to give feedback on, tell us here:__

* The way the bind(event, function) method work is by executing 'function' with 'event' as an argument. Because of that, I had to add the parameters event=None to the save_and_close method otherwise it would throw an error for too many arguments.

### CODE REVIEW

**Comment by lineaba** [comment]
Nice addition, definitely makes it easier for the user. I just tried running it. On my machine I can click enter when I have typed my name, but I can not begin typing my name, without clicking the entry-field first.
Were you trying to solve both of those with this PR, or just the "enter" solution for now?

**Comment by lineaba** [comment]
Also, I know this is not your first PR, but would you mind filling out [this](https://docs.google.com/forms/d/e/1FAIpQLSdQqs9shjcyJTTqbkKjGv85Irxxaljvw0H357zuyrRwXq9_nA/viewform?usp=sf_link) survey if you haven't already. Just fill it out with the info that counted when you made your first pr to our repo :)

**Comment by B-Souty** [comment]
Hey @lineaba I already filled in the survey yesterday I believe 😉 And yes this PR was supposed to cover both. I'll check what's going on and will keep you posted.

**Comment by lineaba** [comment]
Awesome, thanks for doing that, it'll be really helpful.
I have tried to look a little further in to this, because I remembered I had a similar problem for a school project I did last year. I don't know if it is a windows only problem, but the problem is that the tkinter window isn't automatically given focus. The moment I click on the window, the entry field is selected (even if I don't click on the entry field, but just anywhere on the window)
For my class project I ended up not having time to solve the issue, so I don't have a good solution at hand, but what we need to figure out is if there is a way to give the Tkinter window focus when it is launched.

**Comment by B-Souty** [comment]
@lineaba It should be fixed now, I used focus_force() instead of focus_set(). The documentation says it's impolite but it seems to do the trick :stuck_out_tongue: 

>     w.focus_force()
>Force the input focus to the widget. This is impolite. It's better to wait for the window manager to give you the focus. See also .grab_set_global() below.

**Comment by lineaba** [comment]
Cool, that works on my machine. It is fun that they call it rude. The user have launched the program themselves, don't know why it would be considered rude to give focus to the program they have just asked to start :p Either way, works great, I'll merge

**Comment by lineaba** [comment]
That could maybe be a solution. Do you wanna test that out @B-Souty?

2018-04-28 21:24 GMT-07:00 Dan Liberatori <notifications@github.com>:

**Comment by B-Souty** [comment]
Hi @lineaba @garroadran, that was good idea. Unfortunately I just tried it and again it doesn't work on Windows :disappointed: It seems like we won't have a choice but to be rude :/

**Comment by lineaba** [comment]
Fair enough :)

**Pull request merged**
