### PR TITLE
Made a user guide

### PR DESCRIPTION
**Pull request by etiontdn**
__What issue are you solving? (Give #issuenumber)__

#37 

__How do you solve it? (please write this so a human can understand it - bulletpoints are okay)__

Made a guide.md

__If there is something specific in your solution, that you would like the reviewer to give feedback on, tell us here:__

Check it, if there is anything you want to add or any error i would like to hear

_If this is your first pull request to the prog-o-meter project, we would really appreciate it if you would fill out this Google form.
This lets us know more about our contributors, and what we can do to make it easier and nicer to contribute to the prog-o-meter project.
Please submit your answer [here](https://docs.google.com/forms/d/e/1FAIpQLSdQqs9shjcyJTTqbkKjGv85Irxxaljvw0H357zuyrRwXq9_nA/viewform?usp=sf_link) and put an 'x' in the box below._

- [x] It is my first pull request to prog-o-meter, and I have answered the survey

### CODE REVIEW

**Comment by lineaba** [comment]
Hey. Thank you for your contribution :) It looks really nice. I have just, added a few comments, mainly just focusing on adding even more clarity for users who might not be familiar with the command line. It might also be nice to add some screen shots, to help guide people, but that is up to you.

**Comment by etiontdn** [comment]
I was thinking about adding screenshots as well, is there a easy way to attach images to a md file instead of uploading the images to a third party host?

**Comment by lineaba** [comment]
Yes, it is a little silly solution, but what I have found to be easiest, is to Drag and drop the image into a comment here on the issue, and then copy pasting the link that it is gonna create into the .md file. You don't need to actually post the comment you used to drag and drop, you can just delete it. I am not sure why that works, but so far it seems to have been working for me. [here](https://www.youtube.com/watch?v=nvPOUdz5PL4) is the youtube videoguide I found this trick form

**Comment by etiontdn** [comment]
Check the screenshots.

**Comment by lineaba** [comment]
Hey @etiontdn, sorry it took so long for me to review these, I have been travelling and having finals in school. It looks very good with the screenshots. I will merge this in, but I think we could add a little more description about how to run the program, since it is not everybody who are used to using the terminal. 
Would you like to add this? Totally cool if not, then I'll add it as an issue, and someone else can take a look at it in the future :)

**Comment by lineaba** [comment]
User guide added

**Comment by lineaba** [comment]
User guide added

**Comment by etiontdn** [comment]
Great. If there is any grammar error please fix it(Not a native English speaker)
I'm looking forward for contributing to this project again if needed.:smile:

**Comment by lineaba** [comment]
@etiontdn I am not native either, so no worries, but if I find anything I will fix it :) 
You are very welcome to contribute again. If you are interested, you can take a look an see if there is any of the issues you would wanna start working on, and let me know if you have any questions about them :)

**Pull request merged**
