### PR TITLE
Implementing DB and personalization

### PR DESCRIPTION
**Pull request by etiontdn**
__What issue are you solving? (Give #issuenumber)__

I solved the issue #31 and the issue #36 

__How do you solve it? (please write this so a human can understand it - bulletpoints are okay)__

1. I made a file db.py that do all the job on the sqlite3 database
obs: i can change this, depending on the changes or other pull request i can put it inside prog-o-meter.py as well

2. I made some changes to the prog-o-meter.py file so it uses the new implemented db

3. Made a new Window inside the prog-o-meter.py a GUI for personalization
obs: didn't had a lot of idea of how to do it maybe any suggestion of changing it would be welcome 

__If there is something specific in your solution, that you would like the reviewer to give feedback on, tell us here:__
 This is still WIP but i want you to check it out Because it is working but:

1. I still need to remove and change a lot of ugly code

2. I didn't change functions names , it may look strange and confusing

3. I didn't put any docstrings or comments so if the code if confusing ask me, i will add comments and docstrings as soon as i can
obs: i wont have a lot of time these days but i will try to do these as i can.

4. There is a lot of pull requests already so i may want to change as the files change

5. I tried to make the function and variables names easy to understand but it looks messy and ugly 

any feedback is appreciated

_If this is your first pull request to the prog-o-meter project, we would really appreciate it if you would fill out this Google form.
This lets us know more about our contributors, and what we can do to make it easier and nicer to contribute to the prog-o-meter project.
Please submit your answer [here](https://docs.google.com/forms/d/e/1FAIpQLSdQqs9shjcyJTTqbkKjGv85Irxxaljvw0H357zuyrRwXq9_nA/viewform?usp=sf_link) and put an 'x' in the box below._

- [ ] It is my first pull request to prog-o-meter, and I have answered the survey

### CODE REVIEW

**Comment by lineaba** [comment]
Hey, awesome that we are making progress on the database.
I am sorry it has taken me a while to get to your PR. In the meantime I have merged in the new user object, so there is now a user class, with all the functions related to the user. I am sorry that unfortunately that means that we need to rewrite some of the database work. 
The new userobject is in the file user.py - let me know if you would have time to update the database implementation to work with the new object.

**Comment by lineaba** [comment]
For the personalization I think setting the two colors and a motivational phrase is nice for now. We have talked about letting the user add a text for their "next goal", which we can add at a later point.

**Comment by etiontdn** [comment]
I expected that, but i only made this so you can take a look at it as it works.
I will try to adjust to the changes but right now i wont have much time since i am working on a more personal project.
I want to know if i should put it together to the user.py or another file the code is really messy right now and i need to add comments and etc to make the code understandable, i will try to do it once i can. My priority right now is finishing at least the main part of my own project, thanks for the feedback!

**Comment by etiontdn** [comment]
And for the way to set up Colors do you think HEX is alright or maybe another way?
Using only one button to apply all of the changes might be better as well.
 
Also about the start when the user checks I have a Meter and inputs a unknown name,
i needed to make a workaround, but i think a simple warning would be better to fix it

**Comment by lineaba** [comment]
Hey, no stress, we all have plenty of other things to work on, so take your time. 
I don't have much experience with databases, but the your code is easy to read even without, so that is a really big plus for our project.
I think you can make a database.py file if you prefer, but if you think adding it to the user.py file makes more sense, then that is olay with me.

**Comment by etiontdn** [comment]
Sorry if i have been unclear about my last question, i just said i needed to create a new user if the user name wasn't on the database, if that is okay.
About the colors, i thought the same

**Pull request closed without merging**
