### PR TITLE
Issue #29

### PR DESCRIPTION
**Pull request by kevalvc**
__What issue are you solving? (Give #issuenumber)__

#29 Print Encouragements

__How do you solve it? (please write this so a human can understand it - bulletpoints are okay)__

I created a list of different quotes for random days and use a default list for the last day to configure text so that random arrays can be submitted using the list.
I also updated the Hello text upon the completion of the 100 days.

__If there is something specific in your solution, that you would like the reviewer to give feedback on, tell us here:__

This is my first open source update so It might not be the perfect one. If there is something that i can update or improve please help me out, I'll be pleased to learn about it.

_If this is your first pull request to the prog-o-meter project, we would really appreciate it if you would fill out this Google form.
This lets us know more about our contributors, and what we can do to make it easier and nicer to contribute to the prog-o-meter project.
Please submit your answer [here](https://docs.google.com/forms/d/e/1FAIpQLSdQqs9shjcyJTTqbkKjGv85Irxxaljvw0H357zuyrRwXq9_nA/viewform?usp=sf_link) and put an 'x' in the box below._

- [ x ] It is my first pull request to prog-o-meter, and I have answered the survey

### CODE REVIEW

**Comment by lineaba** [comment]
Hey @kevalvc thanks for your contribution, it is awesome to have you join our team. I am sorry it is taking me some time to give you feedback on this pull request, I am having midterms this week, so I am a little busy. I can see this is your first Pullrequest, and I am wondering how you uploaded it?
Often when people make pullrequests I am able to see which specific lines it is that they have changed, but in your version It looks as if the entire "old" version have been removed, and a full "new version" have been set in. This makes it a little hard for me to know where something new have been added. I am very new to open source and github myself, so I am not 100% sure how this happened, but maybe if you can tell me how you added your solution, then we can work together to figure it out. 
I also don't see your list of quotes, only a celebratory gif. Did you maybe forget to add the list of quotes to your commit?

**Comment by kevalvc** [comment]
@lineaba  No problem. What i did was simply after forking it, i committed my changes in my forked repository and then initiated a pull request. I can see the list of encouragements in my commit. Do you want me to remake the pull request? Can you help if I'm doing something wrong?

**Comment by lineaba** [comment]
Hey again, thank you for your patience, I am sorry for being so slow right now. I was just looking at your forked repo, and it doesn't look like their is a list of quotes in your forked repository, so I am a little confused about how they can be in the commit you're seeing. I am very new to this myself, so unfortunately I don't have the solution ready, but I am sure we can work together to solve this. Do you use git on the commandline, or did you do things directly on the github webpage?
First thing I think we should do is figure out if the local version you have on your computer matches the version you have on your branch? Maybe the quotes documents is only stored on your computer, but haven't been added to you github repository?

**Comment by kevalvc** [comment]
Hey, it's absolutely fine. I use git on the command line. I'm pretty sure, I can view the encouragement list in line 56 in the file that I had commit. I'll try repeating the process.

**Comment by lineaba** [comment]
Sorry, you are right about the encouragements they are in line 56. I had misunderstood you, and was looking for a separate file, I didn't think to look in the code. It is my bad!
So that part is great. Now we just need to figure out why your changes does not occur inside the existing file, but appears to be a whole new file :)
When you forked the repo and created a local branch on your computer, did you then modify directly the file that was in the branch, or did you create a copy which you worked on and then added to your branch?

**Comment by kevalvc** [comment]
@lineaba I had modified directly into the same branch, committed and push it. I have initiated a new pull request. Have a look at it. I don't think that is looking like a complete new file :).

**Pull request closed without merging**
