### PR TITLE
Added self.progress() call to self.add_day() to display completed day…

### PR DESCRIPTION
**Pull request by 0xJosh**
…s #52 I noticed that self.progress wasn't actually being called, and this could explain your "redundant variable". I have created a function call to self.progress() inside of self.add_day and this seems to have done the trick. 

This is my first commit, so if there's anything you want to add i will greatly appreciate any feedback; whether it's code related or GitHub etiquette. :smiley:

### CODE REVIEW

**Comment by lineaba** [comment]
Hey, thanks for your first contribution, it is awesome to have you join the team. 

I don't believe that self.progress needs to be called inside self.add_day(), but please let me know if I have misunderstood your point.

Here is a description of how the code was meant to work. If it does not work like that when you run it, we probably have a bug. If that is the case, please let me know, then we can try and fix it.
self.progress was created to be called when the user opens/reopens the program, as a way to show all the days the user have previously completed (For a user who have completed 34 days, the function colors the first 34 squares blue). However, when a user adds a new day by clicking the button, it shouldn't be necessary to call self.progress to go back and color the first 34 squares blue again, they are already blue. All we need is to color the 35th square green. Next time the user opens the program, the first 35 squares will be blue, and the user can click the button to make the 36th square green. There is a difference in color (blue/green), because I wanted there to be a difference between past progress, and the progress made that day. 

The variable that we were talking about in issue #52 was specifically that I have written a for-loop so that  it loops with the variable "i", but that variable isn't actually used for anything inside the loop. I believe that it is generally considered bad style in python to loop with a variable that isn't being used. 

These are the lines in the code where it is happening
```
for i in range(self.GOAL):        # Create a rectangle for each day and add it to the rectangle_list
    rectangle = self.canvas.create_rectangle(LEFT_BOUNDARY, self.CANVAS_HEIGHT/2, LEFT_BOUNDARY+RECTANGLE_WIDENESS, (self.CANVAS_HEIGHT/2)+RECTANGLE_HEIGHT, fill = "white")
    self.rectangle_list.append(rectangle)
    LEFT_BOUNDARY += RECTANGLE_WIDENESS 
```
I have been looking into what we could do about that variable "i", and it looks like a lot of people use the dummy variable "_", to signal that a variable in a for loop is a throwaway value, that will not be used for anything inside the for loop. There is also another solution, which involves using itertools. Personally I prefer keeping things simple and easy to read, so I suggest we use the dummy variable "_", instead of itertools (at least as long as we haven't written tests, to see if we would gain any significant speed by using itertools instead.)

What do you think? And what about you @elheffe80 , would you think that the underscore would be a fair solution to the "i" problem that you originally pointed out?

@0xJosh I am sorry that issue #52 wasn't explained clear enough. You can take a look and see if there are any of the other issues you wanna start solving, or let us know if you have any suggestions for other features that you wanna add to the program 😃

**Comment by 0xJosh** [comment]
Hey @lineaba 

Thanks for getting back to me. I apologize as this wasn't tested fully before submitting a pull request and i am now fully aware of what i had missed. You know i wasn't actually aware of "dummy variables" before you had mentioned this, in fact it's actually taught me a thing or two about iterators, so thank you. 

As far as the issue goes, i can proceed and replace the 'i' with "_" if needed, or if you would prefer to just add this yourself then that can be agreed on. I have some time this evening and will happily look into other issues that i can have a dig at. 

Thanks again, 

J

**Comment by lineaba** [comment]
Hi again. I was looking in to the whole dummy variable thing myself last night. I started this project as a learning experience for myself and others, so I am happy you also learned something. 
It would be very helpful if you would add the dummy variable instead of "i" in the loops where "i" isn't being used. Just notice that there are some loops where the "i" is actually being used in the body of the loop.
You are more than welcome to take a stab at some of the other issues. You could for example take a look at #29 , but if there are others that catch your eye, feel free. Just check if someone have said in the discussion that they are gonna take it, or if there is someone assigned to the issue already (you can check that in the upper right corner)

**Comment by lineaba** [comment]
Hey @0xJosh, just wanted to check in with you on this issue. Did you wanna update the "i" with underscore where necessary? If not, I will add is as an issue for someone else to tackle :) I think the easiest thing will be if I close this pull request, and then you can open a new, if you decide to solve the issue with the iteration variables? Does that sound good?

**Comment by lineaba** [comment]
Hi @0xJosh Since you have been inactive for a while I'll close this pull request and open, so we can add the dummy variables. If you want to contribute again in the future, you are very welcome :)

**Pull request closed without merging**
