### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by lineaba**
Created a template for pullrequest, and link to survey for new contributors
@elheffe80 @garroadran @B-Souty, would one of you be interesting in reviewing my pullrequest?

### CODE REVIEW

**Comment by garroadran** [comment]
Nice! I'll have a look at this later tonight.

**Comment by B-Souty** [comment]
The underscores are here to make the text bold. You can check the rich version of it on the "Files changed" tab. 

I would add that on line 1 we should maybe make it required to at least give the issue number instead of giving the choice between the number and the description. With Github markdown, it's easy to write '#' followed by the issue number and it automatically creates a link. like so: #55
This will make it easier for everyone to know right away what the PR is about.

**Comment by lineaba** [comment]
Great suggestions. 
As @B-Souty mentions, the underscores are to make the text bold in markdown. Otherwise I agree with all your suggestions, and I'll make the appropriate changes :)
Also a quick sidenote. When you review, it is possible to add comments to the document you are reviewing, just hover by the line number, and a little blue box with a plus sign comes up, for you to type your comment for that specific line.

**Comment by garroadran** [comment]
Noted on all the above! Thanks for the clarifications, guys.

**Comment by lineaba** [comment]
Hey @garroadran and @B-Souty I have integrated your suggestions, will one of you take another look and approve if you think it is ready. If not, let me know how I can approve it. Thank you :)

**Comment by lineaba** [comment]
@garroadran @B-Souty would one of you see if the new version is ready for approval, when you have time? Have a nice weekend :)

**Comment by lineaba** [comment]
I would like to point out that using "you guys" can be perceived as exclusive language. I hope for this community to feel welcoming to everyone, so I would like to encourage contributors to avoid gendered language when addressing other contributors. Maybe consider "y'all", "the rest of you", "others", etc. in the future. Our code of conduct states that we want to be using welcoming and inclusive language.

**Pull request merged**
