### PR TITLE
Issue64/user

### PR DESCRIPTION
**Pull request by garroadran**
__What issue are you solving? (Give #issuenumber)__

Addresses issue #64 

__How do you solve it? (please write this so a human can understand it - bulletpoints are okay)__

- Create a new file User.py
- Move file read/write functions to the user class
- Make small changes to ProgressGUI to use the new User object

__If there is something specific in your solution, that you would like the reviewer to give feedback on, tell us here:__

In order to fully make use of a proper User object, it might make sense to rewrite a few more sections of the ProgressGUI class. However, I figured we should take it one step at a time, so I've only made the minimal changes necessary in order to start using a User object.

I think this organization makes sense, because now the logic about how to store and retrieve user data is separate from the GUI logic.

One thing to watch out for is the comment/docstring style in the User.py file.
Since I believe we are moving toward consistent use of PEP8, I had my eye on the PEP8 style guide as I was putting together that file. However, when I made edits to comments in prog-o-meter.py I stuck to the same convention as was already in place because it's important to be consistent within the same file.

### CODE REVIEW

**Comment by lineaba** [comment]
Hey @garroadran, I like the idea of a user object, it will definitely make our code cleaner and easier to navigate. 
I also understand the benefits of seperating the code out into more files, but I am a little worried that this is not necessarily the most beginner friendly approach. I know personally I would struggle with the code being split up if I was new to this codebase, and our program is still relatively simple, to the point where I believe we can still keep most things together. 
But I am open to discuss it, and would like to hear your opinion on it :)

**Comment by garroadran** [comment]
Well, it's certainly a fair point that it might not be the _most_ beginner friendly thing. I can understand that for people who are 100% new to coding, having everything in a single file might make things easier.

However, I think there's a few points to consider.
1. Is it _really_ more beginner-friendly to have everything in one giant file?
Suppose for a minute that I am a brand new contributor and I want to add a feature that lets the user UNDO a day if they pushed the button accidentally. Or maybe I want to add a feature that lets the user add in several days at once, if they forgot to push the button for a week or whatever. In this case, not only do I have to understand how to create the interface so that the user can do that, but I also have to understand how to write to the file on disk, and I have to make sure that whatever I do is not messing up any of the other code around it.

However, if the reading and writing of the file is hidden away inside the user object, I don't need to worry about any of that. I just call the addDays or removeDays method, and it all gets taken care of for me without me needing to worry about the specifics of how the data is stored.

This is a simple example, but it demonstrates the point of encapsulation. By separating things into small pieces, the person who is new to the codebase need only look into the bits that directly affect them. It should also make for smaller commits that are easier to merge.

2. Just how beginner-friendly do we want to go?
There's a certain point that I feel might simply be going too far. There's a reason why modularity and encapsulation are some key concepts in modern software development, and although it can occasionally take some detective work to hunt down where the specific function you're looking for is, I would argue that showing beginners a codebase that is cleanly organized is important from an educational point of view. This doesn't have to be a slippery slope, though. It's a matter of striking a good balance between ease-of-understanding and best practice (if there is such a thing).

**Comment by garroadran** [comment]
By the way, I've been reading up more on PEP8 and I'm going to make some changes to this PR in order to get it up to standard!

**Comment by lineaba** [comment]
You make good arguments, especially about it being easier to contribute, if you don't need to worry about the entire codebase. I do REALLY care about keeping it beginner friendly, even at the cost of cool features, but in this case, I agree that it can actually make our project more beginner friendly.
However, I think we need to take an extra step, in order to merge this in and stay beginner friendly (and keep documentation clear even non-beginners too). I think we should create some sort of "roadmap" (I think it might be called a project organization diagram) which gives an overview of the individual files and their relation.
I can try to work on something like that, but it might take some time before I can have it ready. If you would be interested in creating something like that or have input about how it could be done, that would be cool :)

**Comment by garroadran** [comment]
I wouldn't mind writing something like that up. I can probably do it in the next couple of days. Then I'll submit the PR and you can edit it however you like. I'm thinking I'll put it under `/docs/project_overview.md`.

Does that sound OK?

**Comment by lineaba** [comment]
Sounds great! Thank you :)

2018-05-16 6:16 GMT-07:00 Dan Liberatori <notifications@github.com>:

**Pull request merged**
